transcription_models:
    # should be one of:
    #   base, large, large-v1, large-v2,
    #   tiny, small, medium,
    #   tiny.en, small.en, medium.en
    whisper: base

whisper_settings:
    language: en

    # Whether to detect disfluencies (i.e. hesitations, filler words, repetitions, corrections, etc.)
    # that Whisper model might have omitted in the transcription.
    # This should make the word timestamp prediction more accurate.
    # And probable disfluencies will be marked as special words "[*]".
    detect_disfluencies: false

    # These values changed per https://github.com/openai/whisper/discussions/29#discussioncomment-3726290
    no_speech_threshold: 0.30  # default 0.60
    logprob_threshold: null  # default -1.0

étoile_settings:
    # should be "json" or "tsv"
    export_format: json

ui_themes:
    # see:
    # https://ttkbootstrap.readthedocs.io/en/latest/themes/light/
    # https://ttkbootstrap.readthedocs.io/en/latest/themes/dark/
    stlr: darkly
    astral: cyborg