transcription_models:
    # should be one of:
    #   base, large, large-v1, large-v2,
    #   tiny, small, medium,
    #   tiny.en, small.en, medium.en
    whisper: base

whisper_settings:
    language: en

    # These values given per https://github.com/openai/whisper/discussions/435#discussion-4521080
    max_initial_timestamp: null
    suppress_silence: true
    lower_quantile: 0.05
    lower_threshold: 0.1

    # These values changed per https://github.com/openai/whisper/discussions/29#discussioncomment-3726290
    no_speech_threshold: 0.30  # default 0.60
    logprob_threshold: null  # default -1.0

ui_themes:
    # see:
    # https://ttkbootstrap.readthedocs.io/en/latest/themes/light/
    # https://ttkbootstrap.readthedocs.io/en/latest/themes/dark/
    stlr: darkly
    astral: cyborg